"""treta

Revision ID: 1bc1b11280ea
Revises: d6b935a4fbd6
Create Date: 2026-07-08 16:49:26.745522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bc1b11280ea'
down_revision: Union[str, Sequence[str], None] = 'd6b935a4fbd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('parent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'parent')
    # ### end Alembic commands ###
